### ISSUE TITLE
Unable to update spells list

### ISSUE THREAD

**Issue by rhyokin** [casualshammy/NameplateAuras#137]
**Describe the bug**
When clicking on Spells > "Add spell" or "Click to select spell", the list of spells does not pop up and instead several errors occur.

Errors include:
```
1x AceLocale-3.0-6: NameplateAuras: Missing entry for 'options:spells:icon-border:disabled'
[string "@NameplateAuras\src\options-dialog.lua"]:2332: in function <NameplateAuras\src\options-dialog.lua:1441>
[string "@NameplateAuras\src\options-dialog.lua"]:4420: in function <NameplateAuras\src\options-dialog.lua:4316>
[string "@NameplateAuras\src\options-dialog.lua"]:4466: in function `ShowGUI'
[string "@NameplateAuras\src\NameplateAuras-90100.14-release.lua"]:283: in function `?'
[string "@FrameXML\ChatFrame.lua"]:5157: in function <FrameXML\ChatFrame.lua:5103>
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@FrameXML\ChatFrame.lua"]:4821: in function <FrameXML\ChatFrame.lua:4820>
[string "=[C]"]: in function `ChatEdit_SendText'
[string "@FrameXML\ChatFrame.lua"]:4857: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>
```
```
1x AceLocale-3.0-6: NameplateAuras: Missing entry for 'options:spells:icon-border:builtin'
[string "@NameplateAuras\src\options-dialog.lua"]:2333: in function <NameplateAuras\src\options-dialog.lua:1441>
[string "@NameplateAuras\src\options-dialog.lua"]:4420: in function <NameplateAuras\src\options-dialog.lua:4316>
[string "@NameplateAuras\src\options-dialog.lua"]:4466: in function `ShowGUI'
[string "@NameplateAuras\src\NameplateAuras-90100.14-release.lua"]:283: in function `?'
[string "@FrameXML\ChatFrame.lua"]:5157: in function <FrameXML\ChatFrame.lua:5103>
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@FrameXML\ChatFrame.lua"]:4821: in function <FrameXML\ChatFrame.lua:4820>
[string "=[C]"]: in function `ChatEdit_SendText'
[string "@FrameXML\ChatFrame.lua"]:4857: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>
```
```
1x AceLocale-3.0-6: NameplateAuras: Missing entry for 'options:spells:icon-border:custom'
[string "@NameplateAuras\src\options-dialog.lua"]:2334: in function <NameplateAuras\src\options-dialog.lua:1441>
[string "@NameplateAuras\src\options-dialog.lua"]:4420: in function <NameplateAuras\src\options-dialog.lua:4316>
[string "@NameplateAuras\src\options-dialog.lua"]:4466: in function `ShowGUI'
[string "@NameplateAuras\src\NameplateAuras-90100.14-release.lua"]:283: in function `?'
[string "@FrameXML\ChatFrame.lua"]:5157: in function <FrameXML\ChatFrame.lua:5103>
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@FrameXML\ChatFrame.lua"]:4821: in function <FrameXML\ChatFrame.lua:4820>
[string "=[C]"]: in function `ChatEdit_SendText'
[string "@FrameXML\ChatFrame.lua"]:4857: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>
```
```
1x table index is nil
[string "=[C]"]: in function `rawset'
[string "@NameplateAuras\src\utils.lua"]:19: in function <NameplateAuras\src\utils.lua:17>
[string "@NameplateAuras\src\options-dialog.lua"]:1485: in function <NameplateAuras\src\options-dialog.lua:1478>
[string "@NameplateAuras\src\options-dialog.lua"]:1887: in function <NameplateAuras\src\options-dialog.lua:1883>

Locals:
(*temporary) = <table> {
 173107 = 132310
 126733 = 1386550
 59040 = 132337
 19647 = 136174
 292152 = 237525
 187707 = 1376045
 53271 = 236189
 263786 = 538565
 200108 = 134325
 33206 = 135936
 146877 = 458733
 31983 = 136064
 231665 = 135874
 104773 = 136150
 29453 = 135254
 205369 = 136173
 211011 = 135841
 96231 = 523893
 122783 = 775460
 61934 = 236171
 127963 = 136091
 212638 = 1412207
 3363 = 132250
 6711 = 132181
 251749 = 135803
 215603 = 134153
 236800 = 1392953
 305360 = 236277
 171138 = 237567
 197690 = 132341
 138562 = 607852
 108839 = 610877
 212640 = 1014022
 175697 = 134400
 173562 = 136060
 59847 = 136050
 53480 = 464604
 168877 = 132134
 219399 = 136040
 120044 = 237563
 117526 = 462650
 147362 = 249170
 247609 = 237579
 88010 = 136022
 74001 = 458725
 37527 = 136135
 99 = 132121
 182872 = 136097
 47528 = 237527
 173565 = 136048
 46269 = 136158
 189949 = 132199
 212295 = 135796
 83613 = 237568
 31554 = 132361
 144370 = 614257
 31821 = 135872
 1766 = 132219
 59474 = 136075
 198144 = 1387355
 40875 = 135848
 270697 = 132304
 235314 = 132221
 34376 = 135754
 122470 = 651728
 236437 = 603532
 313030 = 237541
 209194 = 627485
 235450 = 135991
 16974 = 132185
 31230 = 132285
 207167 = 135836
 199804 = 135610
 325208 = 615341
 321702 = 135838
 240190 = 132154
 6940 = 135966
 6552 = 132938
 47788 = 237542
 175548 = 135919
 32365 = 135848
 102342 = 572025
 2139 = 135856
 207319 = 1531513
 321329 = 135864
 144302 = 136012
 248773 = 136177
 203854 = 627606
 115199 = 132153
 262618 = 135968
 261580 = 636333
 197862 = 458225
 151962 = 136025
 124974 = 236764
 123715 = 620827
 296497 = 610611
 191647 = 643246
 220239 = 1247266
 102359 = 538515
 20066 = 135942
 316849 = 458718
 232352 = 132205
 197871 = 1445237
 237261 = 1455893
 88175 = 132322
 85966 = 136184
 189300 = 236303
 111220 = 136146
 163505 = 132122
 346991 = 135975
 119381 = 642414
 230122 = 132297
 115078 = 629534
 312978 = 589118
 260563 = 237524
 6466 = 132395
 55334 = 136214
 31850 = 135870
 31599 = 136163
 183517 = 135799
 25997 = 135904
 57994 = 136018
 136634 = 237430
 87204 = 135945
 198111 = 610472
 259895 = 132275
 255903 = 136189
 29382 = 135896
 135377 = 136100
 32864 = 132298
 118038 = 132336
 199397 = 136230
 22127 = 136100
 132651 = 132092
 116705 = 608940
 15690 = 136175
 187827 = 1247263
 209789 = 1033903
 1022 = 135964
 173898 = 132369
 115781 = 136028
 34694 = 136175
 39082 = 136201
 339721 = 612968
 342247 = 985088
 145057 = 132362
 108396 = 607853
 39077 = 135963
 200196 = 135886
 28200 = 134123
 115176 = 642417
 203272 = 136120
 202619 = 132598
 233490 = 136228
 13847 = 132109
 228048 = 135919
 151327 = 136131
 106839 = 236946
 177566 = 236384
 142671 = 878214
 131947 = 237543
 13750 = 136206
 77628 = 134148
 73564 = 135753
 37683 = 136205
 14268 = 236592
 231627 = 136038
 143939 = 132155
 207811 = 1450144
 132409 = 136174
 43448 = 135834
 74712 = 135805
 41062 = 132343
 8178 = 136039
 93985 = 236946
 34976 = 132487
 183752 = 1305153
 23333 = 132485
 77629 = 134149
 166972 = 132114
 65877 = 135125
 270920 = 1717715
 50322 = 236169
 91802 = 237569
 122860 = 135939
 179057 = 135795
 212619 = 136174
}
(*temporary) = nil
(*temporary) = nil
```

**Comment by casualshammy** [comment]
Thanks for reporting! This bug is fixed in the latest release (90100.15-release)

**Comment by rhyokin** [comment]
Updated, but unfortunately still won't pop up the list... getting another new error (below). Trying to avoid completely purging local settings as I've spent a long time configuring everything, but have re-installed the mod at the very least already.

```
5x table index is nil
[string "=[C]"]: in function `rawset'
[string "@NameplateAuras\src\utils.lua"]:19: in function <NameplateAuras\src\utils.lua:17>
[string "@NameplateAuras\src\options-dialog.lua"]:1485: in function <NameplateAuras\src\options-dialog.lua:1478>
[string "@NameplateAuras\src\options-dialog.lua"]:1887: in function <NameplateAuras\src\options-dialog.lua:1883>

Locals:
(*temporary) = <table> {
 173107 = 132310
 126733 = 1386550
 59040 = 132337
 19647 = 136174
 292152 = 237525
 187707 = 1376045
 53271 = 236189
 263786 = 538565
 200108 = 134325
 33206 = 135936
 146877 = 458733
 31983 = 136064
 231665 = 135874
 104773 = 136150
 29453 = 135254
 205369 = 136173
 211011 = 135841
 96231 = 523893
 122783 = 775460
 61934 = 236171
 127963 = 136091
 212638 = 1412207
 3363 = 132250
 6711 = 132181
 251749 = 135803
 215603 = 134153
 236800 = 1392953
 305360 = 236277
 171138 = 237567
 197690 = 132341
 138562 = 607852
 108839 = 610877
 212640 = 1014022
 175697 = 134400
 173562 = 136060
 59847 = 136050
 53480 = 464604
 168877 = 132134
 219399 = 136040
 120044 = 237563
 117526 = 462650
 147362 = 249170
 247609 = 237579
 88010 = 136022
 74001 = 458725
 37527 = 136135
 99 = 132121
 182872 = 136097
 47528 = 237527
 173565 = 136048
 46269 = 136158
 189949 = 132199
 212295 = 135796
 83613 = 237568
 31554 = 132361
 144370 = 614257
 31821 = 135872
 1766 = 132219
 59474 = 136075
 198144 = 1387355
 40875 = 135848
 270697 = 132304
 235314 = 132221
 34376 = 135754
 122470 = 651728
 236437 = 603532
 313030 = 237541
 209194 = 627485
 235450 = 135991
 16974 = 132185
 31230 = 132285
 207167 = 135836
 199804 = 135610
 325208 = 615341
 321702 = 135838
 240190 = 132154
 6940 = 135966
 6552 = 132938
 47788 = 237542
 175548 = 135919
 32365 = 135848
 102342 = 572025
 2139 = 135856
 207319 = 1531513
 321329 = 135864
 144302 = 136012
 248773 = 136177
 203854 = 627606
 115199 = 132153
 262618 = 135968
 261580 = 636333
 197862 = 458225
 151962 = 136025
 124974 = 236764
 123715 = 620827
 296497 = 610611
 191647 = 643246
 220239 = 1247266
 102359 = 538515
 20066 = 135942
 316849 = 458718
 232352 = 132205
 197871 = 1445237
 237261 = 1455893
 88175 = 132322
 85966 = 136184
 189300 = 236303
 111220 = 136146
 163505 = 132122
 346991 = 135975
 119381 = 642414
 230122 = 132297
 115078 = 629534
 312978 = 589118
 260563 = 237524
 6466 = 132395
 55334 = 136214
 31850 = 135870
 31599 = 136163
 183517 = 135799
 25997 = 135904
 57994 = 136018
 136634 = 237430
 87204 = 135945
 198111 = 610472
 259895 = 132275
 255903 = 136189
 29382 = 135896
 135377 = 136100
 32864 = 132298
 118038 = 132336
 199397 = 136230
 22127 = 136100
 132651 = 132092
 116705 = 608940
 15690 = 136175
 187827 = 1247263
 209789 = 1033903
 1022 = 135964
 173898 = 132369
 115781 = 136028
 34694 = 136175
 39082 = 136201
 339721 = 612968
 342247 = 985088
 145057 = 132362
 108396 = 607853
 39077 = 135963
 200196 = 135886
 28200 = 134123
 115176 = 642417
 203272 = 136120
 202619 = 132598
 233490 = 136228
 13847 = 132109
 228048 = 135919
 151327 = 136131
 106839 = 236946
 177566 = 236384
 142671 = 878214
 131947 = 237543
 13750 = 136206
 77628 = 134148
 73564 = 135753
 37683 = 136205
 14268 = 236592
 231627 = 136038
 143939 = 132155
 207811 = 1450144
 132409 = 136174
 43448 = 135834
 74712 = 135805
 41062 = 132343
 8178 = 136039
 93985 = 236946
 34976 = 132487
 183752 = 1305153
 23333 = 132485
 77629 = 134149
 166972 = 132114
 65877 = 135125
 270920 = 1717715
 50322 = 236169
 91802 = 237569
 122860 = 135939
 179057 = 135795
 212619 = 136174
}
(*temporary) = nil
(*temporary) = nil
```

**Comment by casualshammy** [comment]
I'm sorry you have to purge your settings. Could you please try the latest `beta` (90100.16-beta)?

**Comment by rhyokin** [comment]
No worries, I didn't need to purge the settings just yet!  This seems to have fixed it. Thank you for the prompt responses!

**Comment by casualshammy** [comment]
May I ask you, what spell in your list has gear-like icon?

**Comment by rhyokin** [comment]
> 
> 
> May I ask you, what spell in your list have gear-like icon?

50UL-TR4P - https://www.wowhead.com/item=172915/50ul-tr4p

It's an engineering item which is very useful in some dungeons like Plaguefall to banish a target for 1 minute.
