### ISSUE TITLE
Location of the debuff is automatically changed

### ISSUE THREAD

**Issue by jitaeda** [casualshammy/NameplateAuras#239]
![1](https://github.com/user-attachments/assets/16ef018a-c39a-4198-a705-6533486be7cb)
I placed the debuff location(seperate 2 group) to the left of the name tag and it works very well.

However, as the battle progresses, the location of the debuff changes as follows:
![2](https://github.com/user-attachments/assets/89520b79-d4d2-4d50-84f6-493f0f699f0c)

'reload' does not resolve the issue, must reconnect to restore the debuff to its original place.

For me who just wants a simple addon that displays the debuff you want on the left side of the nameplate, this addon is perfect.
I would appreciate it if you could check what the problem is.
Here is my setting of location.
![3](https://github.com/user-attachments/assets/edc12f6f-3e35-4d1d-aeb6-430f0b5e445b)

Thank you.

**Comment by jitaeda** [comment]
For reference, I'm currently using the NeatPlates addon, but I had the same issue when I used the default nameplates.

**Comment by casualshammy** [comment]
Hi,
That's quite strange: addon doesn't change icon position by itself, especially after some time. I can suggest changing this option to 'right': 
![image](https://github.com/user-attachments/assets/4eb4516a-50a1-4738-820e-97a00e85e273)
Also, disabling this feature may help: 
![image](https://github.com/user-attachments/assets/9768cf27-5bab-4e23-8d4b-c4eab31b0f82)

If it will not help, I'll try to add workaround for NeatPlates.

**Comment by jitaeda** [comment]
Hi
Thank you for quick reply.
I tried both but still when I leveling now,
the debuff location changes at some point.

The target and non-target positions were originally slightly different.
Is this an effect?
I think this phenomenon occurs because there is an animation when clicking and the sizes are different, but I'm not sure.

**Comment by jitaeda** [comment]
I just figured out a trigger.
When I participate in an instance dungeon and exit,
I found that the debuff location changes without fail.

**Comment by jitaeda** [comment]
I deleted NEATPLATES and use BETTERBLIZZPLATES
No errors occur
Sorry about that

**Comment by casualshammy** [comment]
Oh.
I just implemented the new feature and wanted to ask you to update to version `110002.7-release` and then select this option: 
![image](https://github.com/user-attachments/assets/b5a71983-eae1-41c9-819b-1b8632d058d1)
I hope this will fix the position issue.

**Comment by jitaeda** [comment]
First, thank you for the revised version.

In conclusion, I updated to the latest version, but the problem still persisted

I have been using Neatplates' Blizzard theme, and upon checking, other Neatplates themes also showed the same problem
![1](https://github.com/user-attachments/assets/609f51b9-c6f2-4434-b1b4-268e967b3bf7)

I set the settings as you said
Attach icons > no check
Anchor frame > Healthbar
Icon group Anchor > Right
![2](https://github.com/user-attachments/assets/8e70939f-f268-4908-ac3c-05083cc01806)

This is the result screen after setting
The leftmost nameplate is the currently designated target
![3](https://github.com/user-attachments/assets/8c0cf131-e3e7-46df-9459-ee0e2ec2fd45)

I set the debuff locations of the two groups on the target nameplate, and at this time, you can see that the debuff locations of the non-targets are already misaligned

And when I hunt monsters or enter an instance dungeon, as I mentioned earlier, the target's debuff locations change, and the debuff locations of the non-targets are even more misaligned

As I mentioned, this problem only occurs when using Neatplates, and I can use Blizzbetterplate, which I am currently using, without any problems.

I think you have tested the basic plate, so I don't need to mention it.

Today, while I was updating add-ons, I happened to see the change log and noticed that a link to my post was inserted, so I feel a sense of duty to respond.

Thank you.

**Comment by casualshammy** [comment]
Thank you for the feedback!
It's a pity I couldn't fix the bug. Nevertheless, since you found a solution yourself, I consider the ticket resolved.
